// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppEBOS.Entity;

#nullable disable

namespace WebAppEBOS.Entity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230818130139_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAppEBOS.Entity.Entites.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RefAppId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1876),
                            Name = "John",
                            RefAppId = 1,
                            Status = 1,
                            Updated = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1878)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1886),
                            Name = "Emily",
                            RefAppId = 2,
                            Status = 1,
                            Updated = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1886)
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1887),
                            Name = "Michael",
                            RefAppId = 3,
                            Status = 1,
                            Updated = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1888)
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1889),
                            Name = "Sophia",
                            RefAppId = 9,
                            Status = 1,
                            Updated = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1889)
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1890),
                            Name = "William",
                            RefAppId = 5,
                            Status = 1,
                            Updated = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1890)
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1893),
                            Name = "Olivia",
                            RefAppId = 2,
                            Status = 1,
                            Updated = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1893)
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1894),
                            Name = "Liam",
                            RefAppId = 10,
                            Status = 1,
                            Updated = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1894)
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1895),
                            Name = "Ava",
                            RefAppId = 15,
                            Status = 1,
                            Updated = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1895)
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1897),
                            Name = "Noah",
                            RefAppId = 8,
                            Status = 1,
                            Updated = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1898)
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1899),
                            Name = "Isabella",
                            RefAppId = 4,
                            Status = 1,
                            Updated = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1899)
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1900),
                            Name = "James",
                            RefAppId = 1,
                            Status = 1,
                            Updated = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1901)
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1902),
                            Name = "Emma",
                            RefAppId = 6,
                            Status = 1,
                            Updated = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1902)
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1903),
                            Name = "Benjamin",
                            RefAppId = 11,
                            Status = 1,
                            Updated = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1903)
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1904),
                            Name = "Mia",
                            RefAppId = 14,
                            Status = 1,
                            Updated = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1904)
                        },
                        new
                        {
                            Id = 16,
                            Created = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1908),
                            Name = "Ethan",
                            RefAppId = 13,
                            Status = 1,
                            Updated = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1909)
                        },
                        new
                        {
                            Id = 17,
                            Created = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1910),
                            Name = "Charlotte",
                            RefAppId = 3,
                            Status = 1,
                            Updated = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1910)
                        },
                        new
                        {
                            Id = 18,
                            Created = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1911),
                            Name = "Alexander",
                            RefAppId = 5,
                            Status = 1,
                            Updated = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1912)
                        },
                        new
                        {
                            Id = 19,
                            Created = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1913),
                            Name = "Amelia",
                            RefAppId = 9,
                            Status = 1,
                            Updated = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1913)
                        },
                        new
                        {
                            Id = 20,
                            Created = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1914),
                            Name = "Daniel",
                            RefAppId = 7,
                            Status = 1,
                            Updated = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1915)
                        },
                        new
                        {
                            Id = 21,
                            Created = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1916),
                            Name = "Harper",
                            RefAppId = 10,
                            Status = 1,
                            Updated = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1916)
                        },
                        new
                        {
                            Id = 22,
                            Created = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1917),
                            Name = "Matthew",
                            RefAppId = 2,
                            Status = 1,
                            Updated = new DateTime(2023, 8, 18, 13, 1, 39, 600, DateTimeKind.Utc).AddTicks(1918)
                        });
                });

            modelBuilder.Entity("WebAppEBOS.Entity.Entites.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("WebAppEBOS.Entity.Entites.Identity.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("WebAppEBOS.Entity.Entites.Identity.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("WebAppEBOS.Entity.Entites.Identity.UserLogin", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("WebAppEBOS.Entity.Entites.Identity.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("WebAppEBOS.Entity.Entites.Identity.UserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "LoginProvider", "Value");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("WebAppEBOS.Entity.Entites.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
